language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# Latest node
before_install:
  - nvm install 8.3.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH
# Install dependencies
install:
  - yarn install
  - yarn bundle
  - cd py
  - pip install -U pip
  - pip install swiglpk --only-binary swiglpk
  - pip install -e .
  - cd ..
# Run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION = '3.6' ]]; then SCRIPT="coverage"; else SCRIPT="test"; fi
  - yarn $SCRIPT
  - cd py
  - python setup.py test
  - cd ..
# No emails
notifications:
  email: false
# Run with containers
sudo: false
